import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { chromium } from 'playwright'

const base = process.env.BASE_URL ?? 'http://frontend'
const rules = '# Előkészületek\n\nMinden játékos három kártyát kap.\n\n# Körök\n\nEgy körben két akciót végezhetsz. Támadás után nem mozoghatsz.\n\n# Kivétel\n\nA futár támadás után is mozoghat.'
await mkdir('/results', { recursive: true })
const browser = await chromium.launch()
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'hu-HU' })
const page = await context.newPage()
const errors = []
const requestLanguages = new Set()
page.on('pageerror', error => errors.push(error.message))
page.on('request', request => { if (request.url().includes('/api/')) requestLanguages.add(request.headers()['accept-language']) })
const title = `__e2e__ Bilingual admin ${Date.now()}`
async function language(value, scope = page) {
  await scope.getByRole('combobox', { name: /^(Interface language|Felület nyelve)$/ }).selectOption(value)
  await page.waitForFunction(value => document.documentElement.lang === value, value)
}
async function noOverflow() {
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, 'Page overflows horizontally')
}
try {
  await page.goto(`${base}/admin`)
  await page.getByRole('heading', { name: 'Welcome to RuleShelf' }).waitFor()
  assert.equal(await page.locator('html').getAttribute('lang'), 'en', 'English is the default even with a Hungarian browser locale')
  await page.getByLabel('Username', { exact: true }).fill(process.env.ADMIN_USERNAME ?? 'admin')
  await page.getByLabel('Password', { exact: true }).fill('invalid-e2e-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('alert').getByText('Incorrect username or password.', { exact: true }).waitFor()
  await language('hu')
  await page.getByRole('heading', { name: 'Üdv a Szabálytárban' }).waitFor()
  await page.getByRole('alert').getByText('Hibás felhasználónév vagy jelszó.', { exact: true }).waitFor()
  await page.screenshot({ path: '/results/login-hu.png', fullPage: true })
  await language('en')
  await page.getByRole('alert').getByText('Incorrect username or password.', { exact: true }).waitFor()
  await page.getByLabel('Password', { exact: true }).fill(process.env.ADMIN_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('heading', { name: 'Your game shelf' }).waitFor()
  await page.getByText('Loading collection…', { exact: true }).waitFor({ state: 'hidden' })
  await page.screenshot({ path: '/results/admin-desktop-en.png', fullPage: true })
  await page.getByRole('button', { name: 'New game', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel(/Game name/).fill(title)
  await dialog.getByLabel('Edition', { exact: true }).fill('2026 · Test edition')
  assert.equal(await dialog.getByLabel('Rulebook language', { exact: true }).inputValue(), 'en')
  await language('hu', dialog)
  assert.equal(await dialog.getByLabel(/A játék neve/).inputValue(), title)
  assert.equal(await dialog.getByLabel('Szabály nyelve', { exact: true }).inputValue(), 'en', 'Interface switching must not overwrite document metadata')
  await dialog.getByLabel('Rövid leírás').fill('Synthetic bilingual admin test.')
  await dialog.getByRole('button', { name: 'Játék hozzáadása', exact: true }).click()
  await page.getByRole('heading', { name: title, exact: true }).waitFor()
  const games = await (await context.request.get(`${base}/api/games`)).json()
  const game = games.find(g => g.title === title)
  assert.ok(game)
  await writeFile('/results/created-game.json', JSON.stringify({ id: game.id }))
  await page.getByRole('button', { name: 'Szabályanyag feltöltése', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Szöveg beillesztése' }).click()
  await dialog.getByLabel('Dokumentum neve').fill('Bilingual test rules')
  await dialog.getByLabel('Szabályszöveg', { exact: true }).fill(rules)
  await dialog.getByLabel('A dokumentum nyelve').selectOption('hu')
  await language('en', dialog)
  assert.equal(await dialog.getByLabel('Rule text', { exact: true }).inputValue(), rules)
  assert.equal(await dialog.getByLabel('Document language', { exact: true }).inputValue(), 'hu')
  await dialog.getByRole('button', { name: 'Upload and process', exact: true }).click()
  await page.getByRole('button', { name: 'Review', exact: true }).waitFor({ timeout: 60000 })
  await page.screenshot({ path: '/results/admin-document-en.png', fullPage: true })
  await page.getByRole('button', { name: 'Review', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByText('Minden játékos három kártyát kap.', { exact: true }).waitFor()
  assert.equal(await dialog.getByText('3 rule sections', { exact: true }).count(), 1)
  await language('hu', dialog)
  await dialog.getByText('3 szabályrész', { exact: true }).waitFor()
  await dialog.getByLabel('Keresés a feldolgozott dokumentumban').fill('futár')
  const searchResponse = page.waitForResponse(response => response.url().includes('/preview?q=fut%C3%A1r') && response.status() === 200)
  await dialog.getByRole('button', { name: 'Keresés', exact: true }).click()
  await searchResponse
  await page.waitForFunction(() => document.querySelectorAll('.chunk').length === 1)
  await dialog.getByText('A futár támadás után is mozoghat.', { exact: true }).waitFor()
  await page.screenshot({ path: '/results/admin-preview-hu.png', fullPage: true })
  await dialog.getByRole('button', { name: 'Ellenőriztem, közzéteszem' }).click()
  await page.locator('.document-card .badge.published').getByText('Közzétéve').waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await noOverflow()
  await page.screenshot({ path: '/results/admin-mobile-hu.png', fullPage: true })
  await language('en')
  await page.locator('.document-card .badge.published').getByText('Published', { exact: true }).waitFor()
  await noOverflow()
  await page.screenshot({ path: '/results/admin-mobile-en.png', fullPage: true })
  await page.getByRole('button', { name: 'Reprocess', exact: true }).click()
  await page.getByRole('button', { name: 'Review', exact: true }).waitFor({ timeout: 60000 })
  await page.getByText('The previously published version remains available.').waitFor()
  await page.getByRole('button', { name: 'Published version', exact: true }).click()
  await page.locator('.preview-title .badge.published').waitFor()
  await page.getByText('Minden játékos három kártyát kap.', { exact: true }).waitFor()
  await noOverflow()
  await page.getByRole('button', { name: 'Close', exact: true }).click()

  // Backend duplicate-document errors must change language without another request.
  await page.getByRole('button', { name: 'Upload rule material', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Paste text', exact: true }).click()
  await dialog.getByLabel('Rule text', { exact: true }).fill(rules)
  await dialog.getByRole('button', { name: 'Upload and process', exact: true }).click()
  await dialog.getByRole('alert').getByText('This document has already been uploaded for this game.', { exact: true }).waitFor()
  await language('hu', dialog)
  await dialog.getByRole('alert').getByText('Ezt a dokumentumot már feltöltötted ehhez a játékhoz.', { exact: true }).waitFor()
  await dialog.getByRole('button', { name: 'Bezárás', exact: true }).click()
  await page.reload()
  await page.getByRole('heading', { name: 'A játékpolcod' }).waitFor()
  assert.equal(await page.locator('html').getAttribute('lang'), 'hu')
  assert.equal(await page.evaluate(() => localStorage.getItem('ruleshelf.language')), 'hu')
  await page.getByRole('button', { name: 'Kijelentkezés' }).click()
  await page.getByRole('heading', { name: 'Üdv a Szabálytárban' }).waitFor()

  const fresh = await browser.newContext({ locale: 'hu-HU' })
  const freshPage = await fresh.newPage()
  await freshPage.goto(`${base}/admin`)
  await freshPage.getByRole('heading', { name: 'Welcome to RuleShelf' }).waitFor()
  await fresh.close()
  assert.ok(requestLanguages.has('en') && requestLanguages.has('hu'), 'API requests must carry both chosen languages')
  assert.deepEqual(errors, [])
  console.log('PASS: English default, Hungarian/English switching in login/admin/dialogs, live error translation, persistence, unchanged rule content/metadata, processing/search/publication/reprocessing, mobile layout and logout; no JavaScript errors.')
} catch (error) {
  await page.screenshot({ path: '/results/failure.png', fullPage: true }).catch(() => {})
  throw error
} finally {
  await browser.close()
}
